# Generated by Django 3.2.9 on 2021-11-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='grosspay',
            new_name='amount',
        ),
    ]
