# Generated by Django 3.2.9 on 2021-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_grosspay_staff_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=30)),
                ('payment_type', models.CharField(choices=[('MOBILE', 'mobile'), ('BANK', 'bank account')], default='PENDING', max_length=20)),
            ],
        ),
    ]
