# Generated by Django 3.2.9 on 2021-11-17 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payroll_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='created_at',
            new_name='date_processed',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='amount',
            new_name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='insurance',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='insurance_number',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_cover',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_number',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='paye',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='pension',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_email',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='sacco',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_deducted',
            field=models.DecimalField(decimal_places=2, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_pin_number',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='work_email',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
    ]
