# Generated by Django 3.2.9 on 2021-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20211120_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='merchant',
            field=models.CharField(default='MERCHANTS', max_length=100),
        ),
    ]
